@ECHO OFF
SET "Path=%~dp0npm-bin;C:\Users\inbod\.cache\codex-runtimes\codex-primary-runtime\dependencies\node\bin;%SystemRoot%\System32;%SystemRoot%;%SystemRoot%\System32\Wbem"
SET "npm_config_cache=%~dp0npm-cache"
SET "XDG_CONFIG_HOME=%~dp0xdg-config"
SET "XDG_CACHE_HOME=%~dp0xdg-cache"
SET "WRANGLER_HOME=%~dp0wrangler-home"
SET "APPDATA=%~dp0appdata"
SET "LOCALAPPDATA=%~dp0localappdata"
CD /D "C:\Users\inbod\Documents\Codex\2026-06-15\build-a-web-application-called-into"
CALL npm run dev -- --host 127.0.0.1 > "%~dp0dev-server.out.log" 2> "%~dp0dev-server.err.log"
