import type {
  ExactConnection,
  ExactGlAccount,
  ExactMasterDataCache,
  ExactSupplierAccount,
} from "../domain/invoice";
import {
  isMockExactConnection,
  isRealExactMode,
  syncRealExactMasterData,
} from "./exact-api-client";

const glAccounts = {
  office: { code: "4400", name: "Office supplies", isActive: true },
  software: { code: "4420", name: "Software subscriptions", isActive: true },
  hotel: { code: "4510", name: "Hotel expenses", isActive: true },
  airTravel: { code: "4520", name: "Air travel expenses", isActive: true },
  insurance: { code: "4610", name: "Insurance expenses", isActive: true },
  bank: { code: "4690", name: "Bank fees", isActive: true },
  logistics: { code: "4720", name: "Freight and logistics", isActive: true },
  intercompany: { code: "1600", name: "Intercompany purchases", isActive: true },
  services: { code: "4800", name: "Professional services", isActive: true },
} satisfies Record<string, ExactGlAccount>;

const suppliers: ExactSupplierAccount[] = [
  {
    id: "supplier_noordzee",
    code: "70001",
    name: "Noordzee Office Supplies",
    vatNumber: "NL812345678B01",
    iban: "NL91ABNA0417164300",
    chamberOfCommerceNumber: "34123456",
    address: "Keizersgracht 100, Amsterdam",
    country: "NL",
    paymentConditionCode: "21",
    paymentConditionLabel: "7 days",
    defaultGlAccount: glAccounts.office.code,
    defaultGlAccountName: glAccounts.office.name,
    defaultCostCentre: "AMS",
    defaultCostUnit: "OPS",
    isInBodyEntity: false,
  },
  {
    id: "supplier_delta_it",
    code: "70002",
    name: "Delta IT Services",
    vatNumber: "NL855512340B01",
    iban: "NL39RABO0300065264",
    chamberOfCommerceNumber: "55230119",
    address: "Europalaan 21, Utrecht",
    country: "NL",
    paymentConditionCode: "30",
    paymentConditionLabel: "30 days",
    defaultGlAccount: glAccounts.software.code,
    defaultGlAccountName: glAccounts.software.name,
    defaultCostCentre: "AMS",
    defaultCostUnit: "IT",
    isInBodyEntity: false,
  },
  {
    id: "supplier_bright_logistics",
    code: "70003",
    name: "Bright Logistics BV",
    vatNumber: "NL001234567B90",
    iban: "NL02INGB0001234567",
    chamberOfCommerceNumber: "60234111",
    address: "Havenweg 9, Rotterdam",
    country: "NL",
    paymentConditionCode: "30",
    paymentConditionLabel: "30 days",
    defaultGlAccount: glAccounts.logistics.code,
    defaultGlAccountName: glAccounts.logistics.name,
    defaultCostCentre: "RTM",
    defaultCostUnit: "LOG",
    isInBodyEntity: false,
  },
  {
    id: "supplier_google_ireland",
    code: "71001",
    name: "Google Ireland Limited",
    vatNumber: "IE6388047V",
    iban: "IE29AIBK93115212345678",
    chamberOfCommerceNumber: "368047",
    address: "Gordon House, Dublin",
    country: "IE",
    paymentConditionCode: "30",
    paymentConditionLabel: "30 days",
    defaultGlAccount: glAccounts.software.code,
    defaultGlAccountName: glAccounts.software.name,
    defaultCostCentre: "AMS",
    defaultCostUnit: "IT",
    isInBodyEntity: false,
  },
  {
    id: "supplier_booking",
    code: "71002",
    name: "Booking.com BV",
    vatNumber: "NL805734958B01",
    iban: "NL44ABNA0123456789",
    chamberOfCommerceNumber: "31047344",
    address: "Herengracht 597, Amsterdam",
    country: "NL",
    paymentConditionCode: "21",
    paymentConditionLabel: "7 days",
    defaultGlAccount: glAccounts.hotel.code,
    defaultGlAccountName: glAccounts.hotel.name,
    defaultCostCentre: "AMS",
    defaultCostUnit: "TRAVEL",
    isInBodyEntity: false,
  },
  {
    id: "supplier_klm",
    code: "71003",
    name: "KLM Royal Dutch Airlines",
    vatNumber: "NL004983269B01",
    iban: "NL20ABNA0999999999",
    chamberOfCommerceNumber: "33014286",
    address: "Amsterdamseweg 55, Amstelveen",
    country: "NL",
    paymentConditionCode: "21",
    paymentConditionLabel: "7 days",
    defaultGlAccount: glAccounts.airTravel.code,
    defaultGlAccountName: glAccounts.airTravel.name,
    defaultCostCentre: "AMS",
    defaultCostUnit: "TRAVEL",
    isInBodyEntity: false,
  },
  {
    id: "supplier_atlas_insurance",
    code: "71004",
    name: "Atlas Insurance NV",
    vatNumber: "NL009988776B01",
    iban: "NL18INGB0000111122",
    chamberOfCommerceNumber: "27118901",
    address: "Coolsingel 42, Rotterdam",
    country: "NL",
    paymentConditionCode: "30",
    paymentConditionLabel: "30 days",
    defaultGlAccount: glAccounts.insurance.code,
    defaultGlAccountName: glAccounts.insurance.name,
    defaultCostCentre: "AMS",
    defaultCostUnit: "OPS",
    isInBodyEntity: false,
  },
  {
    id: "supplier_inbody_korea",
    code: "80001",
    name: "InBody Co Ltd",
    vatNumber: "KR1208145299",
    iban: "KR990000000000000001",
    chamberOfCommerceNumber: "1208145299",
    address: "625 Eonju-ro, Seoul",
    country: "KR",
    paymentConditionCode: "30",
    paymentConditionLabel: "30 days",
    defaultGlAccount: glAccounts.intercompany.code,
    defaultGlAccountName: glAccounts.intercompany.name,
    defaultCostCentre: "AMS",
    defaultCostUnit: "GROUP",
    isInBodyEntity: true,
  },
  {
    id: "supplier_us_cloud",
    code: "72001",
    name: "US Cloud Inc",
    vatNumber: "US123456789",
    iban: "US00000000000001",
    chamberOfCommerceNumber: "US-2231",
    address: "100 Market Street, San Francisco",
    country: "US",
    paymentConditionCode: "30",
    paymentConditionLabel: "30 days",
    defaultGlAccount: glAccounts.software.code,
    defaultGlAccountName: glAccounts.software.name,
    defaultCostCentre: "AMS",
    defaultCostUnit: "IT",
    isInBodyEntity: false,
  },
  {
    id: "supplier_ambiguous_a",
    code: "73001",
    name: "Acme Supplies BV - Amsterdam",
    vatNumber: "NL123456789B01",
    iban: "NL10ABNA0101010101",
    chamberOfCommerceNumber: "39000001",
    address: "Damrak 10, Amsterdam",
    country: "NL",
    paymentConditionCode: "30",
    paymentConditionLabel: "30 days",
    defaultGlAccount: glAccounts.office.code,
    defaultGlAccountName: glAccounts.office.name,
    defaultCostCentre: "AMS",
    defaultCostUnit: "OPS",
    isInBodyEntity: false,
  },
  {
    id: "supplier_ambiguous_b",
    code: "73002",
    name: "Acme Supplies BV - Eindhoven",
    vatNumber: "NL123456789B01",
    iban: "NL11ABNA0101010102",
    chamberOfCommerceNumber: "39000002",
    address: "High Tech Campus 1, Eindhoven",
    country: "NL",
    paymentConditionCode: "30",
    paymentConditionLabel: "30 days",
    defaultGlAccount: glAccounts.office.code,
    defaultGlAccountName: glAccounts.office.name,
    defaultCostCentre: "EIN",
    defaultCostUnit: "OPS",
    isInBodyEntity: false,
  },
];

export async function syncExactMasterData(
  connection: ExactConnection | null
): Promise<ExactMasterDataCache> {
  if (!connection || connection.status !== "connected") {
    throw new Error("Connect the company Exact account before syncing master data.");
  }

  if (isRealExactMode() && !isMockExactConnection(connection)) {
    return syncRealExactMasterData(connection);
  }

  return createMockExactMasterData(connection.divisionCode);
}

export function createMockExactMasterData(
  divisionCode = "123456"
): ExactMasterDataCache {
  const syncedAt = new Date();
  return {
    source: "exact-online",
    divisionCode,
    lastSyncedAt: syncedAt.toISOString(),
    staleAfter: new Date(syncedAt.getTime() + 30 * 60 * 1000).toISOString(),
    suppliers,
    paymentConditions: [
      { code: "21", label: "7 days", days: 7, isActive: true },
      { code: "30", label: "30 days", days: 30, isActive: true },
      { code: "00", label: "immediately", days: 0, isActive: true },
    ],
    journals: [
      { code: "60", description: "Purchase journal", type: "purchase", isActive: true },
      {
        code: "61",
        description: "Intercompany purchase journal",
        type: "purchase",
        isActive: true,
      },
    ],
    glAccounts: Object.values(glAccounts),
    costCenters: [
      { code: "AMS", description: "Amsterdam", isActive: true },
      { code: "RTM", description: "Rotterdam", isActive: true },
      { code: "EIN", description: "Eindhoven", isActive: true },
    ],
    costUnits: [
      { code: "OPS", description: "Operations", isActive: true },
      { code: "IT", description: "IT", isActive: true },
      { code: "LOG", description: "Logistics", isActive: true },
      { code: "TRAVEL", description: "Travel", isActive: true },
      { code: "GROUP", description: "Group", isActive: true },
    ],
    vatCodes: [
      { code: "4", description: "VAT to claim 21%", percentage: 21, type: "purchase", isActive: true },
      { code: "5", description: "VAT to claim 9%", percentage: 9, type: "purchase", isActive: true },
      { code: "6", description: "VAT to claim 0%", percentage: 0, type: "purchase", isActive: true },
      { code: "7", description: "EU acquisition VAT", percentage: 0, type: "purchase", isActive: true },
      { code: "8", description: "Non-EU acquisition VAT", percentage: 0, type: "purchase", isActive: true },
    ],
    historicalPurchaseBookings: [
      {
        id: "hist_google_workspace",
        supplierAccountId: "supplier_google_ireland",
        descriptionKey: "google-workspace",
        glAccount: glAccounts.software.code,
        vatCode: "7",
        costCentre: "AMS",
        costUnit: "IT",
        accrualFrom: "2026-01-01",
        accrualTo: "2026-06-30",
      },
      {
        id: "hist_klm_flight",
        supplierAccountId: "supplier_klm",
        descriptionKey: "flight-amsterdam-seoul",
        glAccount: glAccounts.airTravel.code,
        vatCode: "6",
        costCentre: "AMS",
        costUnit: "TRAVEL",
      },
    ],
  };
}

export function isExactMasterDataStale(cache: ExactMasterDataCache | null) {
  return !cache || new Date(cache.staleAfter).getTime() <= Date.now();
}
